### ISSUE TITLE
The rank funtion takes over 1 min to execute

### ISSUE THREAD

**Issue by vishalaksh** [Qordobacode/fitbert#16] opened 2020-01-28 05:48 UTC
I am trying to use this library for a real time prediction. But it is taking more than 1 min even on GPU to predict. Here is a [colab link](https://colab.research.google.com/drive/1xoRfp2eagC9sj9DBEpgn0IrAsXJhLNfC).

Here is a screenshot showing the execution time:
![image](https://user-images.githubusercontent.com/2190316/73238671-be91b300-41bf-11ea-8e00-3fa5df8ea039.png)

What could be the possible reason for this latency? Is it pertaining to the library or BERT itself?

Thanks

**Comment by sam-qordoba** [comment] 2020-05-21 21:29
that is strange, it didn't used to. I wonder if this has to do with framework choice? Also in that link, I see:
![image](https://user-images.githubusercontent.com/47401552/82608378-69fbb480-9b6f-11ea-92e3-47f97e54355d.png)

**Comment by sam-qordoba** [comment] 2020-06-09 23:33
Since I can't reproduce, I am closing this

**Closed by sam-qordoba** 2020-06-09 23:33 UTC
Labels: invalid
